##
## EPITECH PROJECT, 2023
## Makefile
## File description:
## Makefile
##

all:
	make -C Ncurses
	make -C SDL2
	make -C SFML

clean:
	make -C Ncurses clean
	make -C SDL2 clean
	make -C SFML clean

fclean:
	make -C Ncurses fclean
	make -C SDL2 fclean
	make -C SFML fclean

re: fclean all
