##
## EPITECH PROJECT, 2023
## Makefile
## File description:
## Makefile
##

all:
	make -C Snake
	make -C Pacman

clean:
	make -C Snake clean
	make -C Pacman clean

fclean:
	make -C Snake fclean
	make -C Pacman fclean

re: fclean all
